version: '3.9'
services:
  api:
    build: ./backend
    container_name: portfolio_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app:ro
  web:
    build: ./frontend/portfolio
    container_name: portfolio_web
    # WICHTIGE ÄNDERUNG HIER: Wir fügen '-- --host' hinzu
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/portfolio:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE=http://localhost:8000